### ISSUE TITLE
SMTP Authentication

### ISSUE THREAD

**Issue by yn-alex** [SimplyStaking/panic_cosmos#2]
I could not find a way to enable SMTP Authentication. Is it supported?

It would be nice to have this feature available. Many hosting providers require SMTP authentication for sending email through their servers. This way it would be easier to setup email alerts.

**Comment by migueldingli1997** [comment]
Hi @yn-alex, this is currently not supported. The following steps should be enough to implement it:

1. Add optional username and password arguments to [email sending util](https://github.com/SimplyVC/panic/blob/master/src/alerting/alert_utils/email_sending.py), and using these to login to the SMTP server.
2. Add username and password to user configuration, including the setup process, so that the node operator has a way of setting these up.

Thank you for the suggestion.

**Comment by migueldingli1997** [comment]
@yn-alex You can try out the code in [miguel/issue#2](/SimplyVC/panic/tree/miguel/issue%232), which has an update to include a username and password in the config for SMTP authentication.
